/** Job Mitra | pulseEvents.ts | src/features/pulse/pulseEvents.ts */

export const PulseEvent = {
  SHIFT_CONFIRMATION: "SHIFT_CONFIRMATION",
  SHIFT_APPLICATION_RECEIVED: "SHIFT_APPLICATION_RECEIVED",
  SHIFT_SHORTLISTED: "SHIFT_SHORTLISTED",
  SHIFT_WAITLISTED: "SHIFT_WAITLISTED",

  APPLICATION_RECEIVED: "APPLICATION_RECEIVED",
  SHORTLISTED: "SHORTLISTED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  PROFILE_UPDATE_NEEDED: "PROFILE_UPDATE_NEEDED",
  OFFER_RECEIVED: "OFFER_RECEIVED",
  SHIFT_CONFIRMATION_REQUIRED: "SHIFT_CONFIRMATION_REQUIRED",
  SHIFT_EMPLOYEE_SELECTED: "SHIFT_EMPLOYEE_SELECTED",

  // Employer — Shift workforce events
  SHIFT_WORKER_CONFIRMED: "SHIFT_WORKER_CONFIRMED",
  SHIFT_WORKER_CANCELLED: "SHIFT_WORKER_CANCELLED",
  SHIFT_POST_COMPLETED: "SHIFT_POST_COMPLETED",
  SHIFT_PLAN_CANCELLED_CONFIRMED_WORKER: "SHIFT_PLAN_CANCELLED_CONFIRMED_WORKER",
  PLAN_CANCELLED: "PLAN_CANCELLED",

  // Employer — Career interview response
  INTERVIEW_ACCEPTED: "INTERVIEW_ACCEPTED",
  INTERVIEW_DECLINED: "INTERVIEW_DECLINED",

  REVIEW_RECEIVED: "REVIEW_RECEIVED",

  EMPLOYMENT_JOINED: "EMPLOYMENT_JOINED",
  EMPLOYMENT_RESIGNATION_SUBMITTED: "EMPLOYMENT_RESIGNATION_SUBMITTED",
  EMPLOYMENT_RESIGNATION_WITHDRAWN: "EMPLOYMENT_RESIGNATION_WITHDRAWN",
  EMPLOYMENT_RESIGNATION_CONFIRMED: "EMPLOYMENT_RESIGNATION_CONFIRMED",
  EMPLOYMENT_TERMINATED: "EMPLOYMENT_TERMINATED",
  EMPLOYMENT_FORCE_COMPLETED: "EMPLOYMENT_FORCE_COMPLETED",
} as const;

export type PulseEvent = (typeof PulseEvent)[keyof typeof PulseEvent];

export type NotificationId = PulseEvent;
